version: "3.6"

volumes:
  postgres_data:

services:
  nginx:
    image: nginx:alpine
    container_name: nz01
    ports:
      - "80:80"
      
    volumes:
      - ./src:/src
      - ./config/nginx:/etc/nginx/conf.d

    depends_on:
      - web
    networks:
      - djangonetwork
    
  web:
    build:
        context: .
        dockerfile: compose/django/Dockerfile
    container_name: dz01
    depends_on:
      - db
    volumes:
      - ./src:/src
    expose:
      - "8000"
    networks:
      - djangonetwork


  db:
    restart: always
    image: postgres:10
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: rootapp123
    volumes:
      - postgres_data:/var/lib/postgresql/data/

networks:
  djangonetwork:
    driver: bridge